#!/bin/sh -
clear

#------------------------------
#          Creditos
#   Miner by JayDDee
#   Script By Rirogan
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

stratum=$1

if [ "$1" = ""  ] 
then
echo "			\033[41;1;37m Minerador CPU by RIROGAN \033[0m "				
sleep 1
echo "\033[34m Você deve adicionar a Pool ou a sua Stratum \033[0m"
echo "\033[44;1;37m Exemplo:   3.238.7.72:6233     \033[0m "
echo "\033[34m ao final do script para que possa minerar corretamente \033[0m"
exit 0
fi

# Aqui se encontra a atualizaão do sistema e a instalação dos plugins e download do minerador.

echo "\033[44;1;37mAtualizando lista de pacotes...\033[0m"
sudo apt-get update > /dev/null
sleep 2
clear

echo "Stratum configurada : \033[01;32m $stratum\033[0m   "
echo "\033[01;31m	 * CPU miner by Rirogan \033[0m   \n"
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get install screen -y > /dev/null
sudo apt-get install build-essential libssl-dev libcurl4-openssl-dev libjansson-dev libgmp-dev gcc autoconf make automake -y > /dev/null
memsize=`free | awk '/Mem/ { print $2 }'`
swapsize=`free | awk '/Swap/ { print $2 }'`
# Quando necessário cria uma partição SWAP de 1GB para máquinas com menos de 1GB de RAM.
if [ "$memsize" -lt "1000000" ]
then
 if [ "$swapsize" -eq "0" ]
 then
  echo "Foi detectado que você possui menos que 1GB de RAM!"
  echo "Será criada uma partição SWAP de 1GB para que o CPUMiner-OPT seja compilado com sucesso."
  sudo dd if=/dev/zero of=/var/swap.img bs=1024k count=1000 > /dev/null
  sudo mkswap /var/swap.img > /dev/null
  sudo chmod 600 /var/swap.img
  sudo swapon /var/swap.img
 fi
fi
sleep 2
clear

echo "\033[44;1;37mBaixando CPUMiner-OPT 24.4...\033[0m"
sudo wget -q https://github.com/JayDDee/cpuminer-opt/archive/v24.4.tar.gz
sleep 2
clear

echo "\033[44;1;37mExtraindo CPUMiner-OPT 24.4...\033[0m"
tar -zxvf v24.4.tar.gz > /dev/null
cd cpuminer-opt-24.4
sleep 2
clear

echo "\033[44;1;37mCompilando CPUMiner-OPT 24.4...(pode demorar um pouco)\033[0m"
rm -f config.status
./autogen.sh || echo done
CFLAGS="-O3 -march=native -Wall" ./configure --with-curl
make -j 4
strip -s cpuminer
# ln ./cpuminer ../cpuminer
cd cpuminer-opt-24.4
sudo mv cpuminer /usr/local/bin/
clear

# Comando iniciador da mineração
#
echo "\033[37;41mSua Mineraçao Foi Iniciada\033[01;0m \n"
cpuminer -o stratum+tcp://$stratum


