#!/bin/sh -
clear

#------------------------------
#          Creditos
#   Miner by JayDDee
#   Script By Rirogan
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

stratum=$1

if [ "$1" = ""  ] 
then
echo "			\033[41;1;37m Minerador CPU by RIROGAN \033[0m "				
sleep 1
echo "\033[34m Você deve adicionar a Pool ou a sua Stratum \033[0m"
echo "\033[44;1;37m Exemplo:   3.238.7.72:6233     \033[0m "
echo "\033[34m ao final do script para que possa minerar corretamente \033[0m"
exit 0
fi

# Aqui se encontra a atualizaão do sistema e a instalação dos plugins e download do minerador.
#
echo "Stratum configurada : \033[01;32m $stratum\033[0m   "
echo "\033[01;31m	 * CPU miner by Rirogan \033[0m   \n"
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get update
sudo apt-get install git -y
sudo apt-get install screen -y
sudo  apt-get install automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++ -y
clear

echo -e "\033[44;1;37mBaixando CPUMiner-OPT v3.8.2...\033[0m"
wget -q https://github.com/JayDDee/cpuminer-opt/archive/v3.8.2.tar.gz
sleep 2
clear

echo -e "\033[44;1;37mExtraindo CPUMiner-OPT v3.8.2...\033[0m"
tar -zxvf v3.8.2.tar.gz > /dev/null
cd cpuminer-opt-3.8.2
sleep 2
clear

echo -e "\033[44;1;37mCompilando CPUMiner-OPT v3.8.2...(pode demorar um pouco)\033[0m"
make distclean || echo clean
rm -f config.status
./autogen.sh || echo done
CFLAGS="-O3 -march=native -Wall" ./configure --with-curl
make -j 4
strip -s cpuminer
# ln ./cpuminer ../cpuminer
sudo mv cpuminer /usr/local/bin/
clear

# Comando iniciador da mineração
#
echo "\033[37;41mSua Mineraçao Foi Iniciada\033[01;0m \n"
cpuminer -o stratum+tcp://$stratum


