#!/bin/sh -
clear

#------------------------------
#          Credits
#   Miner by noncepool
#   By Rirogan
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi

wallet=$1


if [ "$1" = ""  ]
then
echo "			\033[41;1;37m Minerar BTC  $versao \033[0m "				
sleep
echo "\033[34m Você deve adicionar sua carteira de Bitcoin \033[0m"
echo "\033[34m ao final do script para que possa minerar corretamente \033[0m"
exit 0
fi

echo "CARTEIRA CONFIGURADA : \033[01;32m $wallet\033[0m   "
echo "\033[01;31m	 * Minerar BTC na http://zpool.ca \033[0m   \n"
echo "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get update
sudo apt-get install git -y
sudo apt-get install screen -y
sudo apt-get install build-essential libcurl4-openssl-dev gcc make git nano autoconf automake -y
sudo rm -r miner 
git clone https://github.com/noncepool/cpuminer-yescrypt.git miner


echo "\033[44;1;37m Configurando e Compilando Recursos.....     \033[0m "
cd miner 
./autogen.sh 
./configure CFLAGS="-O3" 
make 
cd miner 
sudo mv minerd /usr/local/bin/
clear
screen


echo "\033[37;41mSua Mineraçao Foi Iniciada com sucesso!\033[01;0m \n"
echo "\033[44;1;37m Veja abaixo o status da mineracao:   \033[0m "
minerd -a yescrypt -o stratum+tcp://na.mine.zpool.ca:6233 -u $wallet -p c=BTC

# Att 04/11/2019
