#!/bin/sh -
clear

#------------------------------
#          Credits
#        By Rirogan
#------------------------------

bash=$(echo $BASH)


if [ "$bash" = "/bin/bash" ]
then
exit 0
fi


echo -e "\033[44;1;37m Baixando Pacotes....     \033[0m "
sudo apt-get update
sudo apt-get install git -y
sudo apt-get install maven -y 
sudo apt-get install screen -y
sudo apt-get install nodejs -y 
sudo apt-get install zip unzip -y 
sudo apt-get install build-essential libcurl4-openssl-dev gcc make nano autoconf automake -y

cd miner 
./autogen.sh 
./configure CFLAGS="-O3" 
make 
cd miner 
sudo mv minerd /usr/local/bin/
clear
